### ISSUE TITLE
No provider for NgxSpinnerService

### ISSUE THREAD

**Issue by TLKG** [Napster2210/ngx-spinner#171]
package.json:
```
"dependencies": {
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "ngx-spinner": "^10.0.1",
```

my global CLI version is 10.1.1. If it's the version mismatch, what npm command to install the correct spinner version?

```
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: 
  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: 
    NullInjectorError: No provider for NgxSpinnerService!
NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: 
  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: 
    NullInjectorError: No provider for NgxSpinnerService!
    at NullInjector.get (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:855:1)
    at resolveToken (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:17514:1)
    at tryResolveToken (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:17440:1)
    at StaticInjector.get (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:17266:1)
    at resolveToken (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:17514:1)
    at tryResolveToken (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:17440:1)
    at StaticInjector.get (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:17266:1)
    at resolveNgModuleDep (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:30393:1)
    at NgModuleRef_.get (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:31578:1)
    at resolveDep (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:32143:1)
    at resolvePromise (c:\Users\someone\UI\node_modules\zone.js\dist\zone-evergreen.js:797:1)
    at resolvePromise (c:\Users\someone\UI\node_modules\zone.js\dist\zone-evergreen.js:754:1)
    at c:\Users\someone\UI\node_modules\zone.js\dist\zone-evergreen.js:858:1
    at ZoneDelegate.invokeTask (c:\Users\someone\UI\node_modules\zone.js\dist\zone-evergreen.js:391:1)
    at Object.onInvokeTask (c:\Users\someone\UI\node_modules\@angular\core\fesm2015\core.js:39680:1)
    at ZoneDelegate.invokeTask (c:\Users\someone\UI\node_modules\zone.js\dist\zone-evergreen.js:390:1)
    at Zone.runTask (c:\Users\someone\UI\node_modules\zone.js\dist\zone-evergreen.js:168:1)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:3890:35) {rejection: NullInjectorError: StaticInjectorError(AppMo…nnerComponent -> NgxSpinnerService]: 
  Sta…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask, stack: 'Error: Uncaught (in promise): NullInjectorErr… (http://localhost:4200/polyfills.js:3890:35)', …}
arg1:Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: 
  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: 
    NullInjectorError: No provider for NgxSpinnerService!
NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: 
  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: 
    NullInjectorError: No provider for NgxSpinnerService!
    at NullInjector.get (http://localhost:4200/vendor.js:69108:27)
    at resolveToken (http://localhost:4200/vendor.js:84026:24)
    at tryResolveToken (http://localhost:4200/vendor.js:83952:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:83802:20)
    at resolveToken (http://localhost:4200/vendor.js:84026:24)
    at tryResolveToken (http://localhost:4200/vendor.js:83952:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:83802:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:9498...
message:'Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: \n  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: \n    NullInjectorError: No provider for NgxSpinnerService!\nNullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: \n  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: \n    NullInjectorError: No provider for NgxSpinnerService!\n    at N…localhost:4200/vendor.js:83952:16)\n    at StaticInjector.get (http://localhost:4200/vendor.js:83802:20)\n    at resolveToken (http://localhost:4200/vendor.js:84026:24)\n    at tryResolveToken (http://localhost:4200/vendor.js:83952:16)\n    at StaticInjector.get (http://localhost:4200/vendor.js:83802:20)\n    at resolveNgModuleDep (http://localhost:4200/vendor.js:94989:29)\n    at NgModuleRef_.get (http://localhost:4200/vendor.js:96055:16)\n    at resolveDep (http://localhost:4200/vendor.js:96586:45)'
promise:ZoneAwarePromise {__zone_symbol__state: 0, __zone_symbol__value: NullInjectorError: StaticInjectorError(…mponent -> NgxSpinnerService]: \n  Sta…}
rejection:NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: \n  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: \n    NullInjectorError: No provider for NgxSpinnerService!\n    at NullInjector.get (http://localhost:4200/vendor.js:69108:27)\n    at resolveToken (http://localhost:4200/vendor.js:84026:24)\n    at tryResolveToken (http://localhost:4200/vendor.js:83952:16)\n    at StaticInjector.get (http://localhost:4200/vendor.js:83802:20)\n    at resolveToken (http://localhost:4200/vendor.js:84026:24)\n    at tryResolveToken (http://localhost:4200/vendor.js:83952:16)\n    at StaticInjector.get (http://localhost:4200/vendor.js:83802:20)\n    at resolveNgModuleDep (http://localhost:4200/vendor.js:94989:29)\n    at NgModuleRef_.get (http://localhost:4200/vendor.js:96055:16)\n    at resolveDep (http://localhost:4200/vendor.js:96586:45) {name: 'NullInjectorError', ngTempTokenPath: null, ngTokenPath: Array(2), ngDebugContext: Debug…ext_, …}
stack:'Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: \n  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: \n    NullInjectorError: No provider for NgxSpinnerService!\nNullInjectorError: StaticInjectorError(AppModule)[NgxSpinnerComponent -> NgxSpinnerService]: \n  StaticInjectorError(Platform: core)[NgxSpinnerComponent -> NgxSpinnerService]: \n    NullInjectorError: No provider for NgxSpinnerService!\n …polyfills.js:4128:31)\n    at resolvePromise (http://localhost:4200/polyfills.js:4085:17)\n    at http://localhost:4200/polyfills.js:4189:17\n    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3722:31)\n    at Object.onInvokeTask (http://localhost:4200/vendor.js:103316:33)\n    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3721:60)\n    at Zone.runTask (http://localhost:4200/polyfills.js:3499:47)\n    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:3890:35)'
task:ZoneTask {_zone: Zone, runCount: 0, _zoneDelegates: null, _state: 'notScheduled', type: 'microTask', …}
zone:Zone {_parent: Zone, _name: 'angular', _properties: {…}, _zoneDelegate: ZoneDelegate}
__proto__:Object
```

**Comment by Napster2210** [comment]
@TLKG It's because of version mismatch, your Angular version is v8 then you must use the same version for `ngx-spinner` as well.
User command: `npm install ngx-spinner@8.1.0`
