### ISSUE TITLE
ngx-spinner@12.0.0 and jest unit test throws a ' thrown: "Failed to load ngx-spinner.component.html" '

### ISSUE THREAD

**Issue by loetscher** [Napster2210/ngx-spinner#206]
Environment:
-  Node : v14.15.0
-  Npm : 6.14.8
-  OS : win32 x64

Problem:
- I startet a new Angular app using "ng new ..."
- Migrated this app from karma to jest using https://dev.to/alfredoperez/angular-10-setting-up-jest-2m0l
- jest tests are green
- Added ngx-spinner to the app.component.ts/.html
- `npm run start `works perfectly, spinner is showing up as expected

but jest unit-tests are failing with an error:

```
 FAIL  src/app/app.component.spec.ts
  AppComponent
    × should create the app (127 ms)
    × should have as title 'angular12app' (22 ms)
    × should render title (13 ms)

  ● AppComponent › should create the app

    thrown: "Failed to load ngx-spinner.component.html"

      4 |
      5 | describe('AppComponent', () => {
    > 6 |   beforeEach(async () => {
        |   ^
      7 |     await TestBed.configureTestingModule({
      8 |       imports: [
      9 |         NgxSpinnerModule

      at context.<computed> (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4309:39)
      at src/app/app.component.spec.ts:6:3
```
Steps to reproduce:
1. checkout https://github.com/loetscher/ngx-spinner-ng12-jest/tree/master
2. `npm install`
3. `npm run test`

Note:
Up-/Downgrad to ngx-spinner 11.0.2/13.0.0 "fixes" this problem, see
https://github.com/loetscher/ngx-spinner-ng12-jest/tree/ngx-spinner_11
https://github.com/loetscher/ngx-spinner-ng12-jest/tree/ngx-spinner_13

**Comment by loetscher** [comment]
In the meantime I checkout the v12 tag and did a local build. Using this buildresult all test passes.
It looks like there is an issue with the inlining of the html template in the 12.0.0er release:

bundles\ngx-spinner.umd.js for version 12 is using the **templateUrl**:
```
args: [{
                        selector: 'ngx-spinner',
                        templateUrl: 'ngx-spinner.component.html',
                        styleUrls: ['ngx-spinner.component.css'],
                        changeDetection: i0.ChangeDetectionStrategy.OnPush,
                        animations: [
                            animations.trigger('fadeIn', [
                                animations.state('in', animations.style({ opacity: 1 })),
                                animations.transition(':enter', [
                                    animations.style({ opacity: 0 }),
                                    animations.animate(300)
                                ]),
                                animations.transition(':leave', animations.animate(200, animations.style({ opacity: 0 })))
                            ])
                        ]
```
bundles\ngx-spinner.umd.js local build on base of the v12 Tag is using the **template**:
```
{ type: i0.Component, args: [{
                    selector: 'ngx-spinner',
                    template: "<div [@.disabl ... \r\n  </div>\r\n</div>",
                    changeDetection: i0.ChangeDetectionStrategy.OnPush,
                    animations: [
                        animations.trigger('fadeIn', [
                            animations.state('in', animations.style({ opacity: 1 })),
                            animations.transition(':enter', [
                                animations.style({ opacity: 0 }),
                                animations.animate(300)
                            ]),
                            animations.transition(':leave', animations.animate(200, animations.style({ opacity: 0 })))
                        ])
                    ],
                    styles: ["/*!\r\n * Load Awesome...
```

**Comment by loetscher** [comment]
See https://github.com/thymikee/jest-preset-angular/issues/980#issuecomment-896922180
Adding 
```
"postinstall": "ngcc"
```
to package.json fixed the problem.
See also https://github.com/loetscher/ngx-spinner-ng12-jest/commit/098cf397310dac74bae795676b5f642ebcd3657a
With the ngcc run the test passes now
