### ISSUE TITLE
Help needed, SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by HassanMoin** [Napster2210/ngx-spinner#36]
Hi, I must be missing out on something for this issue to be caused. 
Using Angular 4

I get the following Error in Console when I import your NgxSpinnerModule  from ngx-spinner in app.module

```
(index):17 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:57028/app/app.module.js:21:21)
	    at eval (http://localhost:57028/app/app.module.js:38:4)
	    at eval (http://localhost:57028/app/app.module.js:39:3)
	Evaluating http://localhost:57028/ngx-spinner
	Evaluating http://localhost:57028/app/app.module.js
	Evaluating http://localhost:57028/app/main.js
	Error loading http://localhost:57028/app/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:57028/app/app.module.js:21:21)
	    at eval (http://localhost:57028/app/app.module.js:38:4)
	    at eval (http://localhost:57028/app/app.module.js:39:3)
	Evaluating http://localhost:57028/ngx-spinner
	Evaluating http://localhost:57028/app/app.module.js
	Evaluating http://localhost:57028/app/main.js
	Error loading http://localhost:57028/app/main.js
```

This is my app.module
```
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { APP_BASE_HREF } from '@angular/common';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { routing } from './app.routing';
import { HomeComponent } from './components/home.component';
import { UserService } from './Service/user.service';
import { UserComponent } from './Components/user.component';
import { SearchComponent } from './Components/search.component';
import { FormsModule } from '@angular/forms';
import { NgxSpinnerModule } from 'ngx-spinner';


@NgModule({
    imports: [BrowserModule, ReactiveFormsModule, FormsModule, HttpModule, NgxSpinnerModule, routing],
    declarations: [AppComponent, UserComponent, HomeComponent, SearchComponent],
    providers: [{ provide: APP_BASE_HREF, useValue: '/' }, UserService],
    bootstrap: [AppComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})

export class AppModule { }
```

This is my package.json

```
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.3.4",
    "@angular/compiler": "~4.3.4",
    "@angular/core": "~4.3.4",
    "@angular/forms": "~4.3.4",
    "@angular/http": "~4.3.4",
    "@angular/platform-browser": "~4.3.4",
    "@angular/platform-browser-dynamic": "~4.3.4",
    "@angular/router": "~4.3.4",
    "angular-in-memory-web-api": "~0.3.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.4",
    "ngx-spinner": "1.2.0"
  },
  "devDependencies": {
    "@angular/cli": "^6.1.5",
    "@types/jasmine": "2.5.36",
    "@types/node": "^6.0.46",
    "canonical-path": "0.0.2",
    "concurrently": "^3.2.0",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "typescript": "~2.1.0"
  },
  "repository": {}
}

```
And systemjs.config.js
I think the problem might lie in this file. Is there any declaration missing in systemjs.congfig.js ? 

```
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: '/app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'ng2-bs3-modal': 'npm:/ng2-bs3-modal'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: 'main.js', defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            }
            ,
            'ng2-bs3-modal':
            { main: '/bundles/ng2-bs3-modal.js', defaultExtension: 'js' }
        }
    });
})(this);
```

and tsconfig.json if that is of any use 

```
{
  "compilerOptions": {
    "noStrictGenericChecks": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}
```
I have not yet called the <ngx-spinner> tag in the HTML, as the error fires from app.module.ts.
Any help will be very much appreciated, I looked over the web for similar issues but to no avail. 
Thanks !

**Comment by HassanMoin** [comment]
Fixed this issue by registering the ngx-spinner in the systemjs.config.js file. 

            'tslib': 'node_modules/:tslib/tslib.js',
            'ngx-spinner': 'node_modules/ngx-spinner/ngx-spinner.umd.js'
